---
# tasks file for /etc/ansible/roles/apache
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
#- name: install apache2
 # apt: name=apache2 update_cache=yes state=latest
- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2
- name: copy the ats config file
  copy: src=files/ats.conf dest=/etc/apache2/sites-available
- name: a2ensite ats
  command: a2ensite ats
  notify:
    - restart apache2
- name: a2dissite default
  command: a2dissite 000-default
  notify:
    - restart apache2
