---
rbenv_extra_depends: []
rbenv_apt_packages:
- build-essential
- git
- libcurl4-openssl-dev
- libffi-dev
- libreadline-dev
- libssl-dev
- libxml2-dev
- libxslt1-dev
- zlib1g-dev
- libmysqlclient-dev
- redis-server
